(function(){
  const form=document.querySelector('[data-rfq-form]'); if(!form) return;
  const input=form.querySelector('[data-file-input]'), list=form.querySelector('[data-file-list]'), zone=form.querySelector('[data-drop-zone]'), status=form.querySelector('[data-form-status]'), submit=form.querySelector('[data-submit]'), loaded=form.querySelector('input[name="loaded_at"]');
  if(loaded) loaded.value=String(Math.floor(Date.now()/1000));
  const lang=form.dataset.lang||'en';
  const labels={en:{remove:'Remove',sending:'Sending...',tooMany:'Upload up to 5 files.',single:'Each file must be 8 MB or smaller.',total:'Total file size must be 20 MB or smaller.',type:'This file type is not accepted.',fail:'We could not send the RFQ. Please email the files directly to kisaweng@outlook.com or contact us by WhatsApp.',ok:'Thank you. Your RFQ has been received.\nReference: {ref}\nWe will review the submitted information and contact you using the details provided.'},zh:{remove:'删除',sending:'正在发送……',tooMany:'最多上传5个文件。',single:'单个文件不超过8MB。',total:'文件总大小不超过20MB。',type:'不支持该文件类型。',fail:'询价未能发送，请将图纸直接发送至kisaweng@outlook.com，或通过WhatsApp联系我们。',ok:'感谢提交，您的询价已收到。\n询价编号：{ref}\n我们将审核资料并通过您提供的联系方式与您沟通。'}}[lang];
  const allowed=['pdf','jpg','jpeg','png','step','stp','iges','igs','dwg','dxf','zip']; let files=[];
  const setStatus=(m,c)=>{status.textContent=m;status.className='form-status '+(c||'');};
  const size=n=> n<1048576? Math.round(n/1024)+' KB':(n/1048576).toFixed(1)+' MB';
  function sync(){ const dt=new DataTransfer(); files.forEach(f=>dt.items.add(f)); input.files=dt.files; list.innerHTML=''; files.forEach((f,i)=>{let li=document.createElement('li'); li.innerHTML='<span><span class="file-name"></span> <span class="file-size"></span></span>'; li.querySelector('.file-name').textContent=f.name; li.querySelector('.file-size').textContent='('+size(f.size)+')'; let b=document.createElement('button'); b.type='button'; b.className='file-remove'; b.textContent=labels.remove; b.onclick=()=>{files.splice(i,1);sync();}; li.appendChild(b); list.appendChild(li);}); }
  function add(newFiles){ setStatus('',''); for(const f of newFiles){ const ext=(f.name.split('.').pop()||'').toLowerCase(); if(!allowed.includes(ext)){setStatus(labels.type,'error');continue;} if(f.size>8*1024*1024){setStatus(labels.single,'error');continue;} files.push(f);} if(files.length>5){files=files.slice(0,5);setStatus(labels.tooMany,'error');} let total=files.reduce((s,f)=>s+f.size,0); while(total>20*1024*1024){files.pop(); total=files.reduce((s,f)=>s+f.size,0); setStatus(labels.total,'error');} sync(); }
  input.addEventListener('change',()=>add(input.files)); ['dragenter','dragover'].forEach(e=>zone.addEventListener(e,ev=>{ev.preventDefault();zone.classList.add('is-dragover')})); ['dragleave','drop'].forEach(e=>zone.addEventListener(e,ev=>{ev.preventDefault();zone.classList.remove('is-dragover')})); zone.addEventListener('drop',ev=>add(ev.dataTransfer.files));
  const map={'orfs-hydraulic-fittings':'ORFS Hydraulic Fittings','bsp-hydraulic-adapters':'BSP Hydraulic Adapters','jic-flare-fittings':'JIC Flare Fittings','npt-pipe-fittings':'NPT Pipe Fittings','bulkhead-connectors':'Bulkhead Connectors','hydraulic-hose-fittings':'Hydraulic Hose Fittings','welded-tube-assemblies':'Welded Tube Assemblies','hydraulic-manifold-blocks':'Hydraulic Manifold Blocks','hydraulic-cylinder-parts':'Hydraulic Cylinder Parts','hydraulic-valve-bodies':'Hydraulic Valve Bodies','valve-spools-pistons':'Valve Spools & Pistons','custom-cnc-parts':'Custom CNC Parts'};
  const slug=new URLSearchParams(location.search).get('product'); const sel=form.querySelector('select[name="product_category"]'); if(slug&&map[slug]&&sel){sel.value=map[slug];}
  form.addEventListener('submit',async ev=>{ev.preventDefault(); if(!form.checkValidity()){form.reportValidity();return;} submit.disabled=true; const old=submit.textContent; submit.textContent=labels.sending; setStatus(labels.sending,''); try{const res=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{'Accept':'application/json'}}); const data=await res.json().catch(()=>({})); if(res.ok&&data.success){setStatus(labels.ok.replace('{ref}',data.reference||''),'success'); form.reset(); files=[]; sync(); if(loaded) loaded.value=String(Math.floor(Date.now()/1000));} else {setStatus(data.message||labels.fail,'error');}}catch(e){setStatus(labels.fail,'error');} finally{submit.disabled=false; submit.textContent=old;}});
})();
